import i18next from 'i18next';

i18next.addResources('es', 'ERRORBOUNDARY', {
  TITLE: 'Â¡Oh no, a ocurrido un error!',
  TRY_AGAIN: 'Intenta nuevamente',
  BACK_TO_HOME: 'Volver al inicio',
  ERROR_ALERT: 'Unexpected error occurred',
  TYPE_ERROR: `Error: {{fatal}}`,
  ERROR_MESSAGE:
    '\nWe have reported this to our team ! Please close the app and start again!'
});
